local KB = 1024
local MB = KB * 1024
local GB = MB * 1024

---@type mineral.TuiConfig
return {
  source_colors = {
    netease = "#9D2928",
    bilibili = "#FF8cB0",
    mineral = "#2a6511",
    ["local"] = "green",
  },
  heartbeat_secs = 180,
  script = {
    watchdog_instruction_interval = 2000,
    watchdog_soft_wall_ms = 100,
    watchdog_hard_wall_ms = 1000,
  },
  theme = {
    background = "base",
    base = "#1e1e2e",
    mantle = "#181825",
    crust = "#11111b",
    surface0 = "#313244",
    surface1 = "#45475a",
    overlay = "#6c7086",
    subtext = "#a6adc8",
    text = "#cdd6f4",
    accent = "#cba6f7",
    accent_2 = "#74c7ec",
    red = "#f38ba8",
    yellow = "#f9e2af",
    green = "#a6e3a1",
    peach = "#fab387",
    search_hit = {
      color = "peach",
      modifiers = { "bold", "underline", "italic" },
    },
    dynamic = {
      enabled = true,
      fade_ms = 3000,
    },
    text_alpha = {
      strong = 0.78,
      muted = 0.45,
      faint = 0.22,
      ghost = 0.01,
    },
  },
  keys = {
    play_pause = "<Space>",
    next = "n",
    prev = "p",
    toggle_fullscreen = "z",
    open_search = "s",
    open_queue = "<Tab>",
    open_downloads = "D",
    open_audio_settings = "A",
    quit = "q",
    open_help = "?",
    cycle_lyric = "t",
    enter_search = "/",
    activate = { "l", "<CR>" },
    back = { "h", "<Esc>", "<BS>", "<C-h>" },
    drill_into = "<C-l>",
    cycle_detail_section = { "[", "]" },
    cycle_mode = "m",
    volume_up = { "+", "=" },
    volume_down = { "-", "_" },
    seek_forward = "<Right>",
    seek_backward = "<Left>",
    seek_forward_big = "<S-Right>",
    seek_backward_big = "<S-Left>",
    move_down = { "j", "<Down>" },
    move_up = { "k", "<Up>" },
    move_down_big = "J",
    move_up_big = "K",
    move_first = "g",
    move_last = "G",
    love = "f",
    reorder_down = "<C-j>",
    reorder_up = "<C-k>",
    jump_to_current = "c",
    download = "d",
    dismiss_notice = "x",
    open_action_menu = "o",
    open_copy_menu = "y",
    scroll_line_down = "<C-d>",
    scroll_line_up = "<C-u>",
    scroll_page_down = "<C-f>",
    scroll_page_up = "<C-b>",
  },
  behavior = {
    volume_step = 5,
    seek_step_secs = 5,
    seek_big_step_secs = 30,
    list_jump_rows = 7,
    scrolloff = 3,
    line_scroll_rows = 1,
    page_scroll_rows = 15,
    search_prefetch_rows = 8,
    kill_spawned_daemon_on_exit = true,
    remember_track_pos = "session",
    filter_play_scope = "collection",
  },
  spectrum = {
    style = "bars",
    fft_size = 4096,
    f_min = 20,
    f_max = 20000,
    log_axis_blend = 0.92,
    db_floor = -65.0,
    db_ceil = -6.0,
    peak_mix = 0.5,
    hue_rotate = true,
    baseline_min = 3,
    attack_ms = 50,
    decay_ms = 100,
    release_ms = 200,
    hue_cycle_ms = 30 * 1000,
    cover_fade_ms = 6 * 1000,
    cover_vshift_permille = 200,
    dot_bg_contrast = 0.25,
    bars = {
      show_peak_cap = true,
      show_trail = true,
      spring_peak = true,
      peak_hold_ms = 192,
      peak_fall_ms = 512,
      spring_stiffness = 0.35,
      spring_damping = 0.45,
    },
    scope = {
      column_ms = 16,
    },
    waterfall = {
      push_ms = 64,
      contrast = 1.4,
    },
    terrain = {
      push_ms = 128,
      layers = 8,
      amplitude = 0.30,
      fade_floor = 0.30,
    },
  },
  progress = {
    track = {
      played_alpha = 0.4,
      buffered_alpha = 0.15,
      unbuffered_alpha = 0.04,
    },
    playhead = {
      text_mix = 0.40,
      trail_columns = 6,
      lead_columns = 2,
    },
  },
  waveform = {
    enabled = true,
    contrast = 2.0,
    reveal = {
      duration_ms = 560,
      sweep_ratio = 0.62,
      glow = 0.85,
    },
  },
  cover = {
    protocol = "auto",
    cell_fit = "crop",
    http_timeout_secs = 30,
    debounce_ms = 32,
    download_workers = 12,
    encode_workers = 2,
    decode_pixels = { width = 1024, height = 1024 },
    cache = {
      disk = 4 * GB,
      image = 128 * MB,
      preview = 16 * MB,
      protocol = 64 * MB,
    },
    kmeans = {
      sample_dim = 64,
      swatches = 6,
      seed = 0x5EEDC0DE,
      max_iter = 20,
      converge = 5.0,
      l_min = 8.0,
      l_max = 92.0,
      chroma_min = 8.0,
      min_valid_pixels_pct = 5,
    },
  },
  cover_transition = {
    enabled = true,
    style = "fade",
    duration_ms = 350,
    zoom = {
      scale = 1.12,
    },
  },
  ambient = {
    enabled = true,
    intensity = 0.4,
    sigma = 0.2,
    fade_ms = 5000,
    vignette = {
      strength = 0.75,
      inner = 0.25,
      outer = 0.75,
    },
    drift = {
      enabled = true,
      speed = 1.0,
      sway_pct = 20.0,
    },
    rotate = {
      enabled = true,
      cycle_secs = 30.0,
    },
    pulse = {
      enabled = true,
      depth = {
        intensity = 0.2,
        sigma = 0.25,
        brightness = 0.05,
        vignette = 0.1,
      },
      attack_ms = 70,
      release_ms = 420,
      gain_window_secs = 4.0,
      bass_cutoff_hz = 150.0,
      gamma = 2.6,
      punch = {
        gain = 0.4,
        release_ms = 160,
      },
    },
    anchors = {
      { x = 0.22, y = 0.20, pos = 0, speed_x = 1.05, speed_y = 0.85, phase_x = 0.0, phase_y = 0.0 },
      { x = 0.75, y = 0.28, pos = 250, speed_x = 0.68, speed_y = 0.55, phase_x = 1.7, phase_y = 2.21 },
      { x = 0.50, y = 0.72, pos = 500, speed_x = 0.85, speed_y = 0.72, phase_x = 3.1, phase_y = 4.03 },
      { x = 0.15, y = 0.85, pos = 750, speed_x = 0.58, speed_y = 0.48, phase_x = 4.4, phase_y = 5.72 },
      { x = 0.88, y = 0.80, pos = 1000, speed_x = 0.95, speed_y = 0.80, phase_x = 5.6, phase_y = 1.0 },
    },
  },
  prefetch = {
    radius = 64,
    playback_cover_radius = 3,
    prewarm_ahead = 1,
  },
  search = {
    deep = {
      enabled = true,
      weights = {
        name = 0.6,
        alias = 0.5,
        artist = 0.5,
        album = 0.4,
      },
      locate_on_enter = true,
    },
    channel = {
      detail_debounce_ms = 500,
      sources = { "netease", "bilibili" },
      kinds = { "song", "album", "artist", "playlist", "user" },
    },
  },
  lyrics = {
    attack_ms = 200,
    release_ms = 200,
    highlight_white_mix = 0.45,
    text_alpha = {
      sung = 0.85,
      unsung = 0.5,
      neighbor = 0.5,
      distant = 0,
    },
    fullscreen_line_gap = 1,
    compact_line_gap = 0,
    scroll_ms = 280,
    reattach_ms = 4000,
    overshoot_damping = 1,
    overshoot_max_permille = 6 * 1000,
  },
  animation = {
    frame_tick_ms = 16,
    transition_ms = 288,
    sweep_ms = 288,
    list_scroll_ms = 280,
    minimap_cursor_ms = 240,
    fullscreen_ms = 288,
    controls_press_ms = 220,
    transport = {
      volume_hold_ms = 2000,
      volume_fade_out_ms = 110,
      volume_fade_in_ms = 150,
      mode_hold_ms = 1200,
      controls_hold_ms = 4000,
      mode_reveal_ms = 220,
      mode_resize_ms = 180,
      controls_fade_ms = 220,
    },
    ambient_trail = {
      enter = { delay_ms = 80, ease_ms = 740 },
      exit = { delay_ms = 0, ease_ms = 240 },
    },
    popup_anim_ms = 288,
    toast_anim_ms = 288,
    focus_fade_ms = 288,
    search_focus_morph_ms = 240,
    vinyl_rev_ms = 60000,
    view_sweep = "push",
    menu_reveal = "morph",
    search_focus_transition = "slide",
    spinner_frames = { "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏" },
    marquee = {
      mode = "bounce",
      step_ms = 60,
      pause_ms = 100,
      fade_ms = 300,
      fade_cols = 5,
      loop = {
        gap = "  ✦  ",
      },
      bounce = {
        edge_pause_ms = 800,
      },
    },
  },
  minimap = {
    halo_rows = 5,
    magnet_dots = 2,
  },
  toast = {
    flash_ttl_secs = 4,
  },
  copy = {
    templates = {},
  },
  window_title = {
    enabled = true,
    icons = { playing = "⏸", paused = "▶", idle = "■", disconnected = "⚠" },
    template = {
      { icon = true },
      { field = "title" },
      { field = "artist", prefix = " — " },
    },
    idle = { { icon = true }, { text = "Mineral" } },
    disconnected = { { icon = true }, { text = "Mineral" } },
  },
  layout = {
    min_full_width = 80,
    min_full_height = 24,
    fs_left_pct = 44,
    fs_spectrum = { pct = 28, min = 10, max = 22 },
    transport_height = 5,
    dock_w_pct = 36,
    menu_align = "right",
  },
}
