[package]
name        = "mineral-channel-mineral"
description = "Mineral 内建来源的 channel：跨来源收藏歌单视图"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
rust-version.workspace = true

[dependencies]
mineral-model        = { workspace = true }
mineral-channel-core = { workspace = true }

async-trait = { workspace = true }

[lints]
workspace = true
