[package]
name        = "mineral-config-macros"
description = "Mineral daemon/TUI 配置 schema 与 LuaLS 生成宏"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn   = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
color-eyre = { workspace = true }

[lints]
workspace = true
