[package]
name        = "mineral-persist"
description = "SQLite 连接与通用文件缓存机制"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
rust-version.workspace = true

[dependencies]
thiserror   = { workspace = true }
sea-orm     = { workspace = true }
tokio       = { workspace = true }
rustc-hash  = { workspace = true }
parking_lot = { workspace = true }
mineral-log      = { workspace = true }

[dev-dependencies]
color-eyre  = { workspace = true }
tempfile     = "3"

[lints]
workspace = true
