[package]
name = "mineral-channel-local"
description = "Local filesystem music library and playback"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
arc-swap = { workspace = true }
mineral-channel-core = { workspace = true }
mineral-log = { workspace = true }
mineral-model = { workspace = true }
mineral-playback = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
lofty = { workspace = true }
symphonia = { workspace = true }
rustc-hash = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
uuid = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
mineral-server = { workspace = true }
color-eyre = { workspace = true }
tempfile = "3"
mineral-test = { workspace = true }

[lints]
workspace = true
